name: Schlosskantine Ansbach App Android Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_DISTRIBUTION: 'zulu'
  JAVA_VERSION: '12'
  FLUTTER_VERSION: '3.0.5'
  FLUTTER_CHANNEL: 'stable'
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  flutter:
    name: Run Flutter assigned build appbundle
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
      # Getting dependencies
      - run: flutter pub get
      # Unit tests
      - run: flutter test --dart-define=FB_API_ACCESS_TOKEN=123abc
      # Prepare building: Creating the key.properties file
      - run: |
          echo keyPassword=\${{ secrets.KEY_STORE }} > ${{ env.PROPERTIES_PATH }}
          echo storePassword=\${{ secrets.KEY_PASSWORD }} >> ${{ env.PROPERTIES_PATH }}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{ env.PROPERTIES_PATH }}
          echo storeFile=\${{ github.workspace }}/app/android/key.jks >> ${{ env.PROPERTIES_PATH }}
      # Prepare building: Decoding base64 key into a file
      - run: echo "${{ secrets.KEYSTORE2 }}" | base64 --decode > android/key.jks
      # Building release packages
      - run: flutter build apk --split-per-abi --dart-define=FB_API_ACCESS_TOKEN=${{ secrets.FB_API_ACCESS_TOKEN }}
      - run: flutter build appbundle --dart-define=FB_API_ACCESS_TOKEN=${{ secrets.FB_API_ACCESS_TOKEN }}
      # Save release packages
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: appbundle
          path: ${{ github.workspace }}/app/build/app/outputs/bundle/release
