name: Integration tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_DISTRIBUTION: 'zulu'
  JAVA_VERSION: '12'
  FLUTTER_VERSION: '3.0.5'
  FLUTTER_CHANNEL: 'stable'

jobs:
  flutter:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
        target: [playstore]
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # Run integration test
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: ${{ matrix.target }}
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test/green_path_test.dart -d "macos"
