name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_DISTRIBUTION: 'zulu'
  JAVA_VERSION: '12'
  FLUTTER_VERSION: '3.0.5'
  FLUTTER_CHANNEL: 'stable'

jobs:
  flutter:
    name: Run Flutter assigned build appbundle
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
      # Getting dependencies
      - run: flutter pub get
      # Unit tests
      - run: flutter test --dart-define=FB_API_ACCESS_TOKEN=123abc
